version: '3.8'

services:
  # FortiSwitch Simulator
  fortiswitch-simulator:
    build: ./simulators/fortiswitch
    container_name: fortiswitch-simulator
    ports:
      - "3001:3001"
    volumes:
      - fortiswitch-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=realistic
      - LOG_LEVEL=info

  # FortiAP Simulator
  fortiap-simulator:
    build: ./simulators/fortiap
    container_name: fortiap-simulator
    ports:
      - "3002:3002"
    volumes:
      - fortiap-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=realistic
      - LOG_LEVEL=info

  # Meraki Simulator
  meraki-simulator:
    build: ./simulators/meraki
    container_name: meraki-simulator
    ports:
      - "3003:3003"
    volumes:
      - meraki-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=realistic
      - LOG_LEVEL=info

  # EVE-NG API Proxy - For connecting to EVE-NG instance that hosts FortiGate VMs
  eve-ng-proxy:
    build: ./api-proxy
    container_name: eve-ng-proxy
    ports:
      - "3010:3010"
    environment:
      - EVE_NG_URL=${EVE_NG_URL}
      - EVE_NG_USERNAME=${EVE_NG_USERNAME}
      - EVE_NG_PASSWORD=${EVE_NG_PASSWORD}
    restart: unless-stopped

  # FortiManager API Simulator
  fortimanager-simulator:
    build: ./simulators/fortimanager
    container_name: fortimanager-simulator
    ports:
      - "3004:3004"
    volumes:
      - fortimanager-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=realistic
      - LOG_LEVEL=info

  # FortiAnalyzer API Simulator
  fortianalyzer-simulator:
    build: ./simulators/fortianalyzer
    container_name: fortianalyzer-simulator
    ports:
      - "3005:3005"
    volumes:
      - fortianalyzer-data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=realistic
      - LOG_LEVEL=info

  # Web UI for managing the virtual lab
  ui:
    build: ./ui
    container_name: lab-ui
    ports:
      - "80:80"
    depends_on:
      - fortiswitch-simulator
      - fortiap-simulator
      - meraki-simulator
      - eve-ng-proxy
      - fortimanager-simulator
      - fortianalyzer-simulator
    restart: unless-stopped
    environment:
      - FORTISWITCH_API_URL=http://fortiswitch-simulator:3001
      - FORTIAP_API_URL=http://fortiap-simulator:3002
      - MERAKI_API_URL=http://meraki-simulator:3003
      - FORTIMANAGER_API_URL=http://fortimanager-simulator:3004
      - FORTIANALYZER_API_URL=http://fortianalyzer-simulator:3005
      - EVE_NG_PROXY_URL=http://eve-ng-proxy:3010

volumes:
  fortiswitch-data:
  fortiap-data:
  meraki-data:
  fortimanager-data:
  fortianalyzer-data:
