name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies for FortiSwitch simulator
      working-directory: ./simulators/fortiswitch
      run: npm ci
    
    - name: Build FortiSwitch simulator
      working-directory: ./simulators/fortiswitch
      run: npm run build --if-present
    
    - name: Test FortiSwitch simulator
      working-directory: ./simulators/fortiswitch
      run: npm test --if-present
    
    - name: Install dependencies for FortiAP simulator
      working-directory: ./simulators/fortiap
      run: npm ci
    
    - name: Build FortiAP simulator
      working-directory: ./simulators/fortiap
      run: npm run build --if-present
    
    - name: Test FortiAP simulator
      working-directory: ./simulators/fortiap
      run: npm test --if-present
    
    - name: Install dependencies for Meraki simulator
      working-directory: ./simulators/meraki
      run: npm ci
    
    - name: Build Meraki simulator
      working-directory: ./simulators/meraki
      run: npm run build --if-present
    
    - name: Test Meraki simulator
      working-directory: ./simulators/meraki
      run: npm test --if-present
    
    - name: Install dependencies for UI
      working-directory: ./ui
      run: npm ci
    
    - name: Build UI
      working-directory: ./ui
      run: npm run build --if-present
    
    - name: Test UI
      working-directory: ./ui
      run: npm test --if-present

  docker:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push FortiSwitch simulator
      uses: docker/build-push-action@v3
      with:
        context: ./simulators/fortiswitch
        push: true
        tags: kmransom56/fortinet-lab-fortiswitch:latest
    
    - name: Build and push FortiAP simulator
      uses: docker/build-push-action@v3
      with:
        context: ./simulators/fortiap
        push: true
        tags: kmransom56/fortinet-lab-fortiap:latest
    
    - name: Build and push Meraki simulator
      uses: docker/build-push-action@v3
      with:
        context: ./simulators/meraki
        push: true
        tags: kmransom56/fortinet-lab-meraki:latest
    
    - name: Build and push UI
      uses: docker/build-push-action@v3
      with:
        context: ./ui
        push: true
        tags: kmransom56/fortinet-lab-ui:latest
